name: Enhancement
description: Suggest an enhancement
title: "[Enhancement]: "
labels: ["type/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What should be improved? What are the limitations of the current implications that would be solved by the proposal?
    validations:
      required: true
