name: Create Sonar Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project (without type prefix)'
        required: true
        type: string

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Create Sonar Project for module
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x .github/scripts/sonar-manager.sh
          .github/scripts/sonar-manager.sh -a "create" -p "modules_${{ inputs.project_name }}"
